// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	siogeneric "gitea.slauson.io/slausonio/go-types/siogeneric"
	mock "github.com/stretchr/testify/mock"
)

// AppwriteClient is an autogenerated mock type for the AppwriteClient type
type AppwriteClient struct {
	mock.Mock
}

// CreateEmailSession provides a mock function with given fields: r
func (_m *AppwriteClient) CreateEmailSession(r *siogeneric.AwEmailSessionRequest) (*siogeneric.AwSession, error) {
	ret := _m.Called(r)

	var r0 *siogeneric.AwSession
	var r1 error
	if rf, ok := ret.Get(0).(func(*siogeneric.AwEmailSessionRequest) (*siogeneric.AwSession, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(*siogeneric.AwEmailSessionRequest) *siogeneric.AwSession); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*siogeneric.AwSession)
		}
	}

	if rf, ok := ret.Get(1).(func(*siogeneric.AwEmailSessionRequest) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: r
func (_m *AppwriteClient) CreateUser(r *siogeneric.AwCreateUserRequest) (*siogeneric.AwUser, error) {
	ret := _m.Called(r)

	var r0 *siogeneric.AwUser
	var r1 error
	if rf, ok := ret.Get(0).(func(*siogeneric.AwCreateUserRequest) (*siogeneric.AwUser, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(*siogeneric.AwCreateUserRequest) *siogeneric.AwUser); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*siogeneric.AwUser)
		}
	}

	if rf, ok := ret.Get(1).(func(*siogeneric.AwCreateUserRequest) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSession provides a mock function with given fields: sID
func (_m *AppwriteClient) DeleteSession(sID string) error {
	ret := _m.Called(sID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: id
func (_m *AppwriteClient) DeleteUser(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByID provides a mock function with given fields: id
func (_m *AppwriteClient) GetUserByID(id string) (*siogeneric.AwUser, error) {
	ret := _m.Called(id)

	var r0 *siogeneric.AwUser
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*siogeneric.AwUser, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *siogeneric.AwUser); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*siogeneric.AwUser)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields:
func (_m *AppwriteClient) ListUsers() (*siogeneric.AwlistResponse, error) {
	ret := _m.Called()

	var r0 *siogeneric.AwlistResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*siogeneric.AwlistResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *siogeneric.AwlistResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*siogeneric.AwlistResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEmail provides a mock function with given fields: id, r
func (_m *AppwriteClient) UpdateEmail(id string, r *siogeneric.UpdateEmailRequest) (*siogeneric.AwUser, error) {
	ret := _m.Called(id, r)

	var r0 *siogeneric.AwUser
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *siogeneric.UpdateEmailRequest) (*siogeneric.AwUser, error)); ok {
		return rf(id, r)
	}
	if rf, ok := ret.Get(0).(func(string, *siogeneric.UpdateEmailRequest) *siogeneric.AwUser); ok {
		r0 = rf(id, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*siogeneric.AwUser)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *siogeneric.UpdateEmailRequest) error); ok {
		r1 = rf(id, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePassword provides a mock function with given fields: id, r
func (_m *AppwriteClient) UpdatePassword(id string, r *siogeneric.UpdatePasswordRequest) (*siogeneric.AwUser, error) {
	ret := _m.Called(id, r)

	var r0 *siogeneric.AwUser
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *siogeneric.UpdatePasswordRequest) (*siogeneric.AwUser, error)); ok {
		return rf(id, r)
	}
	if rf, ok := ret.Get(0).(func(string, *siogeneric.UpdatePasswordRequest) *siogeneric.AwUser); ok {
		r0 = rf(id, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*siogeneric.AwUser)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *siogeneric.UpdatePasswordRequest) error); ok {
		r1 = rf(id, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePhone provides a mock function with given fields: id, r
func (_m *AppwriteClient) UpdatePhone(id string, r *siogeneric.UpdatePhoneRequest) (*siogeneric.AwUser, error) {
	ret := _m.Called(id, r)

	var r0 *siogeneric.AwUser
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *siogeneric.UpdatePhoneRequest) (*siogeneric.AwUser, error)); ok {
		return rf(id, r)
	}
	if rf, ok := ret.Get(0).(func(string, *siogeneric.UpdatePhoneRequest) *siogeneric.AwUser); ok {
		r0 = rf(id, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*siogeneric.AwUser)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *siogeneric.UpdatePhoneRequest) error); ok {
		r1 = rf(id, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAppwriteClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewAppwriteClient creates a new instance of AppwriteClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAppwriteClient(t mockConstructorTestingTNewAppwriteClient) *AppwriteClient {
	mock := &AppwriteClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
