// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IamSessionController is an autogenerated mock type for the IamSessionController type
type IamSessionController struct {
	mock.Mock
}

// CreateEmailSession provides a mock function with given fields: c
func (_m *IamSessionController) CreateEmailSession(c *gin.Context) {
	_m.Called(c)
}

// DeleteSession provides a mock function with given fields: c
func (_m *IamSessionController) DeleteSession(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewIamSessionController interface {
	mock.TestingT
	Cleanup(func())
}

// NewIamSessionController creates a new instance of IamSessionController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIamSessionController(t mockConstructorTestingTNewIamSessionController) *IamSessionController {
	mock := &IamSessionController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
